### ISSUE TITLE
Module 'ObjectPath' is not available!

### ISSUE THREAD

**Issue by abdulgaffar** [Textalk/angular-schema-form#190]
I am unable to instantiate schema form.

I loaded scripts in the following order
angular.js
angular-sanitize.js
tv4.js
ObjectPath.js
schema-form.js
bootstrap-decorator.min.js

below is the error.

Error: [$injector:modulerr] Failed to instantiate module myApp due to:
[$injector:modulerr] Failed to instantiate module schemaForm due to:
[$injector:modulerr] Failed to instantiate module ObjectPath due to:
[$injector:nomod] Module 'ObjectPath' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.8/$injector/nomod?p0=ObjectPath
minErr/<@http://localhost:8000/media/js/libs/angular/angular.js:63:12
module/<@http://localhost:8000/media/js/libs/angular/angular.js:1764:1
ensure@http://localhost:8000/media/js/libs/angular/angular.js:1688:38
module@http://localhost:8000/media/js/libs/angular/angular.js:1762:1
loadModules/<@http://localhost:8000/media/js/libs/angular/angular.js:4094:22
forEach@http://localhost:8000/media/js/libs/angular/angular.js:323:11
loadModules@http://localhost:8000/media/js/libs/angular/angular.js:4078:5
loadModules/<@http://

**Comment by rwbaker** [comment]
I'm seeing a similar issue; I'm using Bower and RequireJS:
* angular v1.2.14
* angular-sanitize v1.3.8
* angular-schema-form v0.7.8
* objectpath v1.0.5
* tv4: v1.0.17

**Browser console error:**
```bash
Uncaught Error: [$injector:modulerr] Failed to instantiate module LocationApp due to:
Error: [$injector:modulerr] Failed to instantiate module EditViewControllerModule due to:
Error: [$injector:modulerr] Failed to instantiate module schemaForm due to:
ReferenceError: ObjectPath is not defined
    at new <anonymous> (http://127.0.0.1:8080/lib/angular-schema-form/dist/schema-form.min.js:1:354)
    at invoke (http://127.0.0.1:8080/card-base/lib/angular/angular.js:3762:17)
    at Object.instantiate (http://127.0.0.1:8080/card-base/lib/angular/angular.js:3773:23)
    at provider (http://127.0.0.1:8080/card-base/lib/angular/angular.js:3629:36)
    at Object.provider (http://127.0.0.1:8080/card-base/lib/angular/angular.js:3621:16)
    at http://127.0.0.1:8080/card-base/lib/angular/angular.js:3681:37
    at Array.forEach (native)
    at forEach (http://127.0.0.1:8080/card-base/lib/angular/angular.js:322:11)
    at loadModules (http://127.0.0.1:8080/card-base/lib/angular/angular.js:3668:5)
    at http://127.0.0.1:8080/card-base/lib/angular/angular.js:3675:40
http://errors.angularjs.org/1.2.14/$injector/modulerr?p0=schemaForm&p1=Refe…2F%2F127.0.0.1%3A8080%2Fcard-base%2Flib%2Fangular%2Fangular.js%3A3675%3A40
    at http://127.0.0.1:8080/card-base/lib/angular/angular.js:78:12
    at http://127.0.0.1:8080/card-base/lib/angular/angular.js:3702:15
    at Array.forEach (native)
    at forEach (http://127.0.0.1:8080/card-base/lib/angular/angular.js:322:11)
    at loadModules (http://127.0.0.1:8080/card-base/lib/angular/angular.js:3668:5)
    at http://127.0.0.1:8080/card-base/lib/angular/angular.js:3675:40
    at Array.forEach (native)
    at forEach (http://127.0.0.1:8080/card-base/lib/angular/angular.js:322:11)
    at loadModules (http://127.0.0.1:8080/card-base/lib/angular/angular.js:3668:5)
    at http://127.0.0.1:8080/card-base/lib/angular/angular.js:3675:40
http://errors.angularjs.org/1.2.14/$injector/modulerr?p0=EditViewController…2F%2F127.0.0.1%3A8080%2Fcard-base%2Flib%2Fangular%2Fangular.js%3A3675%3A40
    at http://127.0.0.1:8080/card-base/lib/angular/angular.js:78:12
    at http://127.0.0.1:8080/card-base/lib/angular/angular.js:3702:15
    at Array.forEach (native)
    at forEach (http://127.0.0.1:8080/card-base/lib/angular/angular.js:322:11)
    at loadModules (http://127.0.0.1:8080/card-base/lib/angular/angular.js:3668:5)
    at http://127.0.0.1:8080/card-base/lib/angular/angular.js:3675:40
    at Array.forEach (native)
    at forEach (http://127.0.0.1:8080/card-base/lib/angular/angular.js:322:11)
    at loadModules (http://127.0.0.1:8080/card-base/lib/angular/angular.js:3668:5)
    at createInjector (http://127.0.0.1:8080/card-base/lib/angular/angular.js:3608:11)
http://errors.angularjs.org/1.2.14/$injector/modulerr?p0=LocationApp&p1=Err…2F%2F127.0.0.1%3A8080%2Fcard-base%2Flib%2Fangular%2Fangular.js%3A3608%3A11)
```

**require-config.js**
```javascript
requirejs.config({
    paths: {
        'angular-schema-form'  : requirejs.localLib + 'angular-schema-form/dist/schema-form.min',
        'angular-sanitize'     : requirejs.localLib + 'angular-sanitize/angular-sanitize',
        'bootstrap-decorator'  : requirejs.localLib + 'angular-schema-form/dist/bootstrap-decorator.min',
        'bootstrap-custom'     : requirejs.localLib + 'custom-schema-form/bootstrap-custom.min',
        'custom-schema-form'   : requirejs.localLib + 'custom-schema-form/src/schema-form',
        'ObjectPath'           : requirejs.localLib + 'objectpath/lib/ObjectPath',
        'js'                   : requirejs.appSrc + 'js',
        'utility'              : requirejs.appSrc + 'js/utility'
    },
    shim: {
        'angular-sanitize'     : ['angular'],
        'angular-schema-form'  : ['angular', 'angular-sanitize', 'ObjectPath', 'tv4'],
        'custom-schema-form'   : ['angular-schema-form'],
        'bootstrap-decorator'  : ['custom-schema-form'],
        'bootstrap-custom'     : ['angular', 'custom-schema-form', 'bootstrap-decorator']
    }
});
```

**Comment by asadighi** [comment]
I am having the same exact issue. Is there any fix there or should i create a temporary shim for it? (which I rather to not do that).

**Comment by a-laughlin** [comment]
The issue is that Angular Schema Form doesn't support requirejs.  Both tv4 + objectPath do, so they don't export window variables when require exists.  The solution is to wrap Schema Form the same way that ObjectPath and tv4 do, like so:

```js
(function (global, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['angular','ObjectPath','tv4'], factory);
  } else if (typeof module !== 'undefined' && module.exports){
    // CommonJS. Define export.
    module.exports = factory(angular,ObjectPath,tv4);
  } else {
    // Browser globals
    global['schema-form'] = factory(angular,ObjectPath,tv4);
  }
})(this,function(angular,ObjectPath,tv4){
  var deps = [];
  // ... the rest of the Angular Schema Form code here.
});
```

**Comment by a-laughlin** [comment]
Same solution for the bootstrap decorator.

**Comment by nikolassv** [comment]
As ObjectPath does also define an angularJs module if angularJs is loaded, angular-schema-form should define ObjectPath as a module dependency. Then it could simply inject the ObjectPath service where needed.

**Comment by thomask** [comment]
I am having the exact same issue. I am using schemaForm in conjunction with the Bootstrap decorator. No require.js.

**Comment by dwikle** [comment]
@Dervisevic Is there a solution for this?  Can angular-schema-form be updated to work with requirejs per the comment from @a-laughlin ?

**Comment by Dervisevic** [comment]
I guess it can, I'm not sure tho, nothing I've looked into. Maybe @davidlgj knows more, I assume a PR would be welcome.

**Comment by artemshapovalov** [comment]
Please add requirejs wrapper for bootstrap decorator  to version 0.8.2

**Comment by Dervisevic** [comment]
Pull Requests welcome.

**Comment by artemshapovalov** [comment]
I see wrapper for schemaForm, but for bootstrap decorator it's missing. Please help me find  right commit

**Comment by cava23** [comment]
+1 I'm trying to figure this out as well.
